### PR TITLE
Updated Article X

### PR DESCRIPTION
**Pull request by vidyakanekal**
Addressing Issue #9, affiliation with outside groups

### CODE REVIEW

**Comment by vmm2297** [comment]
Wait so thumbs down means no affiliation right? I put thumbs down assuming that

**Comment by vmm2297** [comment]
I say no affiliation for now, but can amend to be apart of OSSN (like Alex linked before) after we get the ground running with us just at UCSD

**Comment by asg017** [comment]
👍 means that you're good with this Pull Request, which says "no affiliation" - 👎 means that you're not good with this Pull Request. So if you say no affiliation, then 👍 this PR!

**Comment by asg017** [comment]
its got 5 👍 so /cdn.vox-cdn.com/uploads/chorus_asset/file/13607754/Screen_Shot_2018_12_06_at_4.55.26_PM.png)

**Pull request merged**
